### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by krizajb** [craftcms/commerce-mollie#1]
I am trying to use Mollie gateway plugin and I am stuck with how one should use it. I entered the Mollie test API key but don't know how payment form should look like. Mollie plugin doesn't implement `getPaymentFormHtml`. I've tried making a [payment form](https://github.com/craftcms/commerce-docs/blob/v2/en/making-payments.md) but I am again getting lost since I have no clue how to get `paymentForm`.

Not entirely sure how field mapping between craft commerce and gateways (e.g. mollie) work, but I would assume that there is universal API for all gateways or should one just look up the gateway [documentation](https://docs.mollie.com/reference/v2/payments-api/create-payment) on how to create payment? 

Anyway, as you can see I am a bit lost. When using Stripe plugin gateway everything works without any problem since plugin implements everything needed for an easy integration with the front end.

Reading this [thread](https://craftcms.stackexchange.com/questions/18012/omnipay-mollie-implementation) the OP says that Mollie is an off-site implementation. This is probably the reason I am dealing with above mentioned issues. Either way, I still don't know how to use this gateway plugin to get it working.

> Nevermind, I did not understand that Mollie is an off-site implementation. So the checkout just redirects you to the Mollie environment. If you want to implement on-site payments using Mollie you'd have to write your own logic I presume.

**Comment by krizajb** [comment]
Got it working, the problem in my case was that Mollie doesn't support localhost, ended up using ngrok and got it working locally. Oh It ended up working with default shop templates.

> The webhookUrl must be reachable from Mollie’s point of view, so you cannot use localhost. If you want to use webhook during development on localhost, you must use a tool like ngrok to have the webhooks delivered to your local machine.

**Comment by andris-sevcenko** [comment]
Glad you got it working!
