### ISSUE TITLE
Webhooks from Mollie don't work

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/commerce-mollie#16]
Hi,

We've installed the latest version of your extension, 2.0.1. But the webhooks are not working.
The webhook URL and the returnUrl are the same. This should not be the case, because the webhook url should only handle the payment and not return a redirect. But not sure if this is the exact reason why it fails, but if you visit the webhook url with a normal browser it processes the payment, only the mollie call doesn't trigger the same.

Steps to reproduce:
1. install and configure the latest commerce and version 2.0.1 of commerce mollie
2. make an order, go to mollie to pay, then close the tab (to prevent manually triggering the url on redirect).
3. Check the mollie logs for the webhook, it says the call failed.

**Comment by lenvanessen** [comment]
Can be closed, the culprit was Snaptcha. Because all the post request front-end are filtered for the unique key, that Mollie doesn't contain, it throws a 403. 

Is fixed now, but as a improvement might be good to use a seperate url for the mollie webhooks, that isn't the same as the one customers are redirected back to

**Comment by andris-sevcenko** [comment]
I'm leaving this open then as a reminder that the webhooks for Mollie must be fully tested. I can't promise anything about the timeline, though.

**Comment by bartrylant** [comment]
@lenvanessen I'm having the same issue but I'm not using Snaptcha anywhere, so I'm wondering what's going wrong on my site. I'm on discord with this name, hit me up if you have a moment. (Didn't find your contact info.)

**Comment by bartrylant** [comment]
@andris-sevcenko It looks like the webhook url that is sent to Mollie is
`https://www.xxxxxxxx.nl/index.php?p=actions/commerce/payments/complete-payment&commerceTransactionHash=d0fd3391805cd32a308dec8a179016a8`

However, Mollie says they get this in return:
`HTTP/1.1 400 Bad Request`

**Comment by stenvdb** [comment]
I can confirm this issue here as well. Unfortunately [disabling CSRF protection](https://github.com/craftcms/commerce-mollie/issues/7#issuecomment-479384432) doesn't help (besides, that should be done in the controller if necessary, see https://github.com/craftcms/cms/issues/1303). Would love to see a fix for this.

**Comment by lukeholder** [comment]
Fixed in commerce. See https://github.com/craftcms/commerce/issues/900

**Comment by lukeholder** [comment]
Also removed out-of-date instructions within docs.
