### ISSUE TITLE
Mollie down

### ISSUE THREAD

**Issue by driesbonte** [craftcms/commerce-mollie#21]
Mollie was temporary down and I took our craft website down as well.
Are you able to fix this so that the website it self doesn’t go down and only the payment function is disabled or any other solution?

`GuzzleHttp\Exception\ServerException: Server error: `GET https://api.mollie.com/v2/methods` resulted in a `503 Service Unavailable`

**Comment by driesbonte** [comment]
Today we had the same issue again. When will this issue be addressed?

**Comment by janhenckens** [comment]
We use Mollie on a couple of Commerce installs too and, while Mollie indeed down, the site itself is still up. Submitting the form to the to go to the payment just refreshes the page.

We're aren't listing payment methods from Mollie though, which is sounds like you are @driesbonte ?
