### ISSUE TITLE
Order confirmation not being sent when using Mollie

### ISSUE THREAD

**Issue by MetaDevelopment** [craftcms/commerce-mollie#24]
### Description
I recently upgraded a webshop from Commerce 2 to Commerce 3 and quickly noticed that order confirmation emails were no longer being sent.

The email settings appear correct after testing and when I go into an order and press "Send Email" in the top right, the confirmation email gets sent.

The confirmation email is linked to the default order status, so should be sent as soon as an order is placed/paid.

There is nothing in the (error) logs.

When I use the dummy gateway in a test environment, the confirmation email does get sent automatically. So might this be an issue with the Mollie payment gateway?

### Steps to reproduce

Setup a confirmation email and use the Mollie gateway for the payment. This is difficult to test in a different/clean environment due to the required Mollie-subscription/setup.

### Additional info

- Craft version: 3.4.13
- Craft Commerce version: 3.1.1
- Mollie for Craft Commerce version: 2.1.1
- PHP version: 7.2.30

**Comment by nfourtythree** [comment]
Hi @MetaDevelopment 

This is something that we are unable to reproduce.

At a guess, it is likely something in the email template that is causing the issue.

Something that might cause an issue is the warning that appears at the bottom of the [order status emails documentation](https://docs.craftcms.com/commerce/v3/order-status-emails.html#html-email-template-path).

If you continue to see problems, please email support@craftcms.com with copies of the email template, `composer.json`, `composer.lock` and a database backup.

Thanks.

**Comment by MetaDevelopment** [comment]
Hi nfourtythree,

Thanks for the reply. I seems unlikely that the email template would be causing the issue, since:

"when I go into an order and press "Send Email" in the top right, the confirmation email gets sent."

and

"When I use the dummy gateway in a test environment, the confirmation email does get sent automatically."

I'll e-mail Craft support with those files, hopefully this can get resolved quickly.

**Comment by nfourtythree** [comment]
Hi @MetaDevelopment 

Thank you for the info in the support email I have replied to it.

For clarity, this turned out to be an issue with the email template.

Thanks.
