### ISSUE TITLE
Mollie test payment page returns to the site only for "paid" payment status

### ISSUE THREAD

**Issue by nikolenko-dmitriy** [craftcms/commerce-mollie#25]
When there is more than 1 payment method, mollie handles correctly status "paid" only, with the redirection to the original website. For any other payment status selected it only returns to the general page with the list of available methods without any additional message.

Tested with "Test API key" on 2 different mollie accounts and I have got the same result in both cases.

Details:
Craft CMS Version 3.4.17.1
Craft Commerce Version 3.1.3
Mollie for Craft Commerce Version 2.1.1

**Comment by jornwildenbeest** [comment]
When will this issue be addressed?

**Comment by nfourtythree** [comment]
Hi All

I was just wondering if someone could give me a little bit more information on what is happening.

A video or steps to reproduce would be great.

I have just tried to reproduce the issue with the latest version of Commerce and the example templates and couldn't see any issues. Here are my findings for the statues:

## Open
Remains on the mollie page as expected (webhook is not called, [as stated by the mollie docs](https://docs.mollie.com/payments/status-changes))

> **open** - The payment has been created, but nothing else has happened yet. This is not a status Mollie will call your webhook for.


## Paid
Redirects to the site and completes the order.

## Failed
Redirects to the site with appropriate "failed" error message. A failed transaction is recorded.
![]()

## Canceled

## Expired

**Comment by nfourtythree** [comment]
Hi All

I was just wondering if someone could give me a little bit more information on what is happening.

A video or steps to reproduce would be great.

I have just tried to reproduce the issue with the latest version of Commerce and the example templates and couldn't see any issues. Here are my findings for the statues:

## Open
Remains on the mollie page as expected (webhook is not called, [as stated by the mollie docs](https://docs.mollie.com/payments/status-changes))

> **open** - The payment has been created, but nothing else has happened yet. This is not a status Mollie will call your webhook for.


## Paid
Redirects to the site and completes the order.

## Failed
Redirects to the site with appropriate "failed" error message. A failed transaction is recorded.
![](https://p191.p3.n0.cdn.getcloudapp.com/items/DOuoAL1j/Screenshot%202020-12-07%20at%2008.53.46.png?v=62497a4237bbd55dbc7f93750ae74cb9)

## Canceled
Redirects to the site with appropriate "canceled" error message. A failed transaction is recorded.
![](https://p191.p3.n0.cdn.getcloudapp.com/items/RBu9qbRE/Screenshot%202020-12-07%20at%2008.54.15.png?v=4a6c50dfd3078c48c4d3038a7cadfdc0)

## Expired
Webhook is triggered and a failed transaction is recorded. User remains on Mollie.
![](https://p191.p3.n0.cdn.getcloudapp.com/items/GGu2ob9b/Screenshot%202020-12-07%20at%2008.56.02.png?v=ff76b0932887e8a6e3e6154cdb337d34)

![](https://p191.p3.n0.cdn.getcloudapp.com/items/8Lun7WL0/Image%202020-12-07%20at%209.01.29%20am.png?v=7c7cb40ba2b0a04c07d4e478ab785f6c)

**Comment by nfourtythree** [comment]
Hi All,

With no further information, we are going to close this issue.

If you find specific steps to reproduce this issue with the latest version of Commerce and this plugin please update this issue with those steps.

We can then reopen the issue and investigate.

Thanks.
