### ISSUE TITLE
Successful transactions are not being processed properly

### ISSUE THREAD

**Issue by jerome2710** [craftcms/commerce-mollie#26]
There seems to be a recent issue which sometimes causes successful transactions to not being processed properly. In some cases, the transaction even appears twice, causing the order to be 'Overpaid'. As well as `craft\commerce\elements\Order::EVENT_AFTER_ORDER_PAID` not being called, which harms our business logic.

Could this be investigated and addressed?

<img width="975" alt="Schermafbeelding 2020-06-09 om 10 01 34" src="https://user-images.githubusercontent.com/4600095/84126305-0661fa00-aa3e-11ea-98e6-4c12754dc818.png">

<img width="363" alt="Schermafbeelding 2020-06-09 om 10 02 46" src="https://user-images.githubusercontent.com/4600095/84126329-0e219e80-aa3e-11ea-80a4-bd5e09fc81a5.png">

**Comment by jerome2710** [comment]
Additional; this issue does not seem limited to a specific payment method. iDEAL, credit cards, Bancontact, they all seem to fail sometimes.

Versions:
- PHP 7.2.31
- Craft Pro 3.4.20
- Craft Commerce 3.1.4
- Mollie for Craft Commerce 2.1.1

**Comment by jerome2710** [comment]
Any updates on this issue? I see that @nfourtythree is maintaining this repository and just released an update. Could this be related?

**Comment by nfourtythree** [comment]
Hi @jerome2710 

Sorry I missed this issue I think I got confused as I assumed it was issue #23 

Please see [this comment](https://github.com/craftcms/commerce-mollie/issues/23#issuecomment-645545091) for the resolution of this issue.

Thanks!
