### ISSUE TITLE
Http\Adapter\Guzzle6\Client' not found

### ISSUE THREAD

**Issue by pepsDev** [craftcms/commerce-mollie#35]
### Description

Can't open Orders in CP after craftcms/commerce-mollie 3.0 update.

```
Error
Class 'Http\Adapter\Guzzle6\Client' not found
```

### Additional info

- Craft version: 3.6.12
- Commerce version: 3.3.0
- PHP version: 7.4.18

**Comment by lukeholder** [comment]
Likely a composer cache issue, this worked for others:

Please delete your `vendor` folder, delete your composer cache (run `composer clearcache`) and then run `composer install` again.

Let us know...

**Comment by pepsDev** [comment]
It worked. Thanks!
