### ISSUE TITLE
TypeError when trying to submit payment form

### ISSUE THREAD

**Issue by chlsydkysr** [craftcms/commerce-mollie#49]
### Description
I migrated to Craft 4 & Commerce 4 and wasn't able to place orders with Mollie as gateway.
When submitting the payment form, I receive the following error message:
**TypeError
craft\commerce\omnipay\base\RequestResponse::getRedirectData(): Return value must be of type array, null returned**

I noticed that the function "getRedirectData()" in omnipay/mollie/src/Message/Response/FetchTransactionResponse.php currently returns null. When changing this to return $this->data, I am able to submit the payment and everything works again as suspected.

### Additional info

- Craft version: Pro 4.4.5
- PHP version: 8.0.27
- Database driver & version: MySQL 5.7.40
- Plugins & versions: Mollie for Craft Commerce 4.1.0

**Comment by robin-braibant-alpine** [comment]
Same issue here. 
First opened an issue at the Commerce repository: https://github.com/craftcms/commerce/issues/3126

**Comment by lukeholder** [comment]
@alpine-digital @chlsydkysr @mediabeastnz

This should be fixed in commerce-mollie 4.1.0.1 - Please update and let us know how it goes.
