### ISSUE TITLE
Fix commerce-omnipay dependency

### ISSUE THREAD

**Issue by jerome2710** [craftcms/commerce-mollie#5]
The composer.json requires `^1.0.0` as the version of the commerce-omnipay dependency. There has been an update to fix an error with this module and v1.0.1 has been released. Could you adjusted the composer.json to require `^1.0` so the update will be applied? Thanks.

**Comment by andris-sevcenko** [comment]
As per [composer docs](https://getcomposer.org/doc/articles/versions.md#caret-version-range-), the version requirement is correct. Perhaps try clearing your composer caches before updating?
