### ISSUE TITLE
Digital product licences not created

### ISSUE THREAD

**Issue by Moorst** [craftcms/commerce-mollie#8]
When processing an order for a digital product with Mollie the licence isn't created. 

I've only tried this with the Bitcoin payment option in test mode, but I've raised this issue in the craft commerce slack channel and another user has noted they're having the experience with other payment options (iDeal, bancontact).

Interestingly, the order is set to complete but a paid date is missing;

![image](https://user-images.githubusercontent.com/6151408/50379123-39d97a80-0638-11e9-95e5-459a488134fc.png)

**Comment by andris-sevcenko** [comment]
This is a bug with Craft Commerce (craftcms/commerce#600) and will be fixed in the next release of Commerce.
