### ISSUE TITLE
Support environment variables syntax in settings (Craft 3.1)

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce-mollie#9]
Support variables like $MOLLIE_API_KEY

See also https://github.com/craftcms/aws-s3/issues/35

**Comment by creativeorange** [comment]
Works like a charm. Can't wait for this PR to get approved!

**Comment by andris-sevcenko** [comment]
Just cut a release with this.

**Comment by boboldehampsink** [comment]
For consistency this probably also needs these changes applied:
- https://github.com/craftcms/mailgun/commit/3401ff357f91beeffeac2294c34dcfeee7810890
- https://github.com/craftcms/mailgun/commit/2d542ce9a577871c38531ce5e7438f9556957345

**Comment by creativeorange** [comment]
Good stuff! :-) 
Have a nice day!
